/**
 * Draft status type
 */
export type DraftStatus = 'pending' | 'reviewed' | 'edited' | 'sent' | 'deleted';

/**
 * Urgency level type
 */
export type UrgencyLevel = 'high' | 'medium' | 'low';

/**
 * Auto-generated draft model
 */
export interface AutoGeneratedDraft {
  id: number;
  draftId: string;
  originalEmailId: number;
  subject: string;
  body: string;
  tone: string;
  urgencyLevel: UrgencyLevel;
  relationshipType: string;
  status: DraftStatus;
  createdAt: string; // ISO timestamp
  reviewedAt?: string;
  sentAt?: string;
  userEdited: boolean;
  editCount: number;
  processingTime: string; // "1000ms" format
  contextUsed?: Record<string, any>;
  // Include original email data for webhook-first architecture
  originalEmail?: {
    subject: string;
    from: string;
    date: string;
    isRead: boolean;
    preview: string;
    gmailId?: string;
  };
}

/**
 * API response for auto-drafts endpoint
 */
export interface DraftsResponse {
  message: string;
  drafts: AutoGeneratedDraft[];
  total: number;
}

/**
 * API response for individual draft
 */
export interface DraftResponse {
  message: string;
  draft: AutoGeneratedDraft;
}

/**
 * Draft update request body
 */
export interface DraftUpdateRequest {
  subject: string;
  body: string;
}

/**
 * Draft action response
 */
export interface DraftActionResponse {
  message: string;
  draftId: number;
  [key: string]: any; // For additional response fields
}